<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_submenu_Details_top_ACC</name>
   <tag></tag>
   <elementGuidId>dd2db221-bd94-4446-858f-0af9465133f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//ul[@class='submenu'])[3]/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//ul[@class='submenu'])[3]/li[4]</value>
   </webElementProperties>
</WebElementEntity>
