<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_submenu_Details_top_ACont</name>
   <tag></tag>
   <elementGuidId>19074be7-d2f9-49be-b2f9-e0a824b61f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//ul[@class='submenu'])[3]/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//ul[@class='submenu'])[3]/li[5]</value>
   </webElementProperties>
</WebElementEntity>
