<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_submenu_Services_top_About_country</name>
   <tag></tag>
   <elementGuidId>f2278c4f-45cd-4baa-84d8-6bdb21e3888c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//ul[@class='submenu'])[5]/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//ul[@class='submenu'])[5]/li[2]</value>
   </webElementProperties>
</WebElementEntity>
