<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ver_Payment_OK</name>
   <tag></tag>
   <elementGuidId>70b515bd-04f1-48f3-be3e-853f55e5db88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@onclick=&quot;closeAlertPayment(this)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;body_alert_payment_ok&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;closeAlertPayment(this)&quot;]</value>
   </webElementProperties>
</WebElementEntity>
