<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>set_Trainig_level</name>
   <tag></tag>
   <elementGuidId>0ffd2c10-4ccd-4f0a-8e7e-4a16249a8ea0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(.//*[@id='change_tour_type1'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[@id='change_tour_type1'])[5]</value>
   </webElementProperties>
</WebElementEntity>
