<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>set_Most_of_Acc</name>
   <tag></tag>
   <elementGuidId>aa3c4f16-78a9-43ff-a7e2-318e1551b73e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(.//*[@id='change_tour_type1'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[@id='change_tour_type1'])[4]</value>
   </webElementProperties>
</WebElementEntity>
