<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ver_detail_report_page</name>
   <tag></tag>
   <elementGuidId>6d75ac69-8644-47f2-9df2-d1a640b3cf96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_author</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kama-Meru is an impressive waterfall bathed by the Aponwao River in the heart of the Gran Sabana, a national park that turns out to be one of the largest reservoirs of biodiversity in the world, located in Venezuela. &quot;Kama-Merú&quot; means &quot;swallow&quot; in the Pemón Taurepan language, the indigenous ethnic group that inhabits the area for centuries ... This name is because it has &quot;swallowed&quot; many lives...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;author_activity&quot;)/div[@class=&quot;body_popup_author&quot;]/div[@class=&quot;text_author&quot;]</value>
   </webElementProperties>
</WebElementEntity>
