<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ver_actions_for_flag</name>
   <tag></tag>
   <elementGuidId>ffb2c127-6df7-417c-817d-ea3c295fa3fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//div[@class=&quot;list_for_flag&quot;]</value>
   </webElementProperties>
</WebElementEntity>
