<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_3rd_lvl_Off-road</name>
   <tag></tag>
   <elementGuidId>8d44e7ce-3681-4e11-9f2b-a1ceed6cf1bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='point-type-subsubcategory']/div[2]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
