<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_3rd_lvl_categories</name>
   <tag></tag>
   <elementGuidId>a5fdc8fe-7402-4b8c-ba8b-4e55b350d933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='point-type-subsubcategory']/div[1]</value>
   </webElementProperties>
</WebElementEntity>
