<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_2nd_lvl_Ground</name>
   <tag></tag>
   <elementGuidId>e3809868-8f12-4658-9872-40f9f5f1a647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='point-type-subcategory']/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='point-type-subcategory']/div[2]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
