<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_picker_Select_date</name>
   <tag></tag>
   <elementGuidId>cdf9559c-2728-48ae-ae0f-d458501c2a5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='ui-datepicker-div']/table/tbody/tr[4]/td[4]/a</value>
   </webElementProperties>
</WebElementEntity>
