<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_picker_Year</name>
   <tag></tag>
   <elementGuidId>d899b9b4-5cad-4df6-a660-d2ec96c20263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//select[@data-handler=&quot;selectYear&quot;]</value>
   </webElementProperties>
</WebElementEntity>
