<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Report_row_link_to_details</name>
   <tag></tag>
   <elementGuidId>80dbd98b-aff1-4112-9309-fb41e5f9e61b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(.//span[@class='visited_country'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//span[@class='visited_country'])[1]</value>
   </webElementProperties>
</WebElementEntity>
