<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>but_add_description_Packing</name>
   <tag></tag>
   <elementGuidId>fbf21a41-e974-4baf-9c8b-dc0de3160f4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@date-rel=&quot;2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@date-rel=&quot;2&quot;]</value>
   </webElementProperties>
</WebElementEntity>
