<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>but_add_photo_Packinglist</name>
   <tag></tag>
   <elementGuidId>928e3932-9030-4d32-98df-e3a973b460b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@date-rel=&quot;1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@date-rel=&quot;1&quot;]</value>
   </webElementProperties>
</WebElementEntity>
