<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Gender_Female</name>
   <tag></tag>
   <elementGuidId>a565c190-5709-4fc5-8887-cf425771f64b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[1]/main/div[1]/div[1]/div/div[1]/table[1]/tbody/tr/td[2]/div[2]/i[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[1]/main/div[1]/div[1]/div/div[1]/table[1]/tbody/tr/td[2]/div[2]/i[1]</value>
   </webElementProperties>
</WebElementEntity>
