<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>top_avatar_photo</name>
   <tag></tag>
   <elementGuidId>3e6b8f41-fef4-43ea-972e-dbf76e521824</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar_photo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;author_lists&quot;)/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;list slick-slide slick-current slick-active&quot;]/div[@class=&quot;tooltip&quot;]/div[@class=&quot;table-author&quot;]/div[@class=&quot;cell&quot;]/a[1]/div[@class=&quot;avatar_photo&quot;]</value>
   </webElementProperties>
</WebElementEntity>
